server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://admin:123456@34.139.16.103:27017/mujipark?authSource=admin
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  kafka:
    bootstrap-servers: 34.139.16.103:9092
    consumer:
      group-id: result-1
      enable-auto-commit: true
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

#      max-poll-records: 1


#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
