version: '3.0'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - /home/wby8456/mongo/data:/data/db
      - /home/wby8456/mongo/logs:/var/log/mongodb
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
#      Change the ip to your own external ip
      KAFKA_ADVERTISED_HOST_NAME: 34.75.183.226
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181