spring:
  data:
    mongodb:
      uri: mongodb://admin:123456@34.139.235.122:27017/mijnpark?authSource=admin
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  application:
    name: sense-count
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  kafka:
#    bootstrap-servers: 34.138.176.208:9092
#    consumer:
#      group-id: sense-1
#      max-poll-records: 1
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8083